#!/bin/bash

#-input proj
PROJECT=spinnaker-launcher-main

ZONE_PRIME=us-east1-a

#REGION=us-central1

ACC=parthi.poc@gmail.com

echo $PROJECT
echo $ZONE_PRIME
echo $ACC
#echo $REGION

# set project & zone
gcloud config set project $PROJECT

gcloud config set compute/zone $ZONE_PRIME 
