#!/bin/bash

#-input proj
PROJECT=packers-148014

ZONE_PRIME=us-central1-a

#REGION=us-central1

ACC=parthi.geo@gmail.com

echo $PROJECT
echo $ZONE_PRIME
echo $ACC
#echo $REGION

# set project & zone
gcloud config set project $PROJECT

gcloud config set compute/zone $ZONE_PRIME 
